---
title: "PLP2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Strings

string <- "string"
print(string)
```

```{r}
## Numerics (Integer)

numericint <- 5L
print(numericint)
```

```{r}
## Numerics (Float)

numericfloat <- 5.5
print(numericfloat)
```

```{r}
## Interactions between types of numerics

print(numericint + numericfloat)
print(numericint * numericfloat)
print(numericint / numericfloat)
```

```{r}
## Lists

list <- list(2, 4, 6, 8)
print(list)
```

```{r}
## Booleans

booleant <- TRUE
print(booleant)

booleanf <- FALSE
print(booleanf)
```

```{r}
## Hashes

hashexample <- hash()
hashexample[["key1"]] <- "val1"
hashexample[["key2"]] <- "val2"
hashexample[["key3"]] <- "val3"
print(hashexample)
```

```{r}
## String/numeric interactions: operations

x = "1" + 2
print(2)

# Will throw error: "non-numeric argument to binary operator"
```

```{r}
## String/numerics interactions: lists

snlist1 <- list("1", 2, 3)
snlist2 <- list(1, 2.5, 3)

print(snlist1)
print(snlist2)
```

```{r}
## Arithmetic operations

1+2     # Addition
1*2     # Multiplication
1/2     # Division
1^2     # Exponents
1%%2    # Division remainder
1L%/%2L # Integer division
```

```{r}
## Logical operations

1+2 == 3  # "Equal to"
1+2 != 3  # "Not equal to"

1<2 # Less than
1>2 # Greater than

1<=2  # Less than or equal to
1>=2  # Greater than or equal to

1 == 1 & 2 == 2   # 1 is equal to 1 AND 2 is equal to 2
1 != 1 & 2 == 2   # 1 is not equal to 1 AND 2 is equal to 2


```


