---
title: "PLP4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
trueval <- TRUE
falseval <- FALSE

if(trueval == TRUE){
  print("trueval is true")
} else {
  print("trueval is false")
}

if(falseval == TRUE){
  print("falseval is true")
} else {
  print("falseval is false")
}
```

```{r}
if(trueval == TRUE & falseval == FALSE){
  print("trueval is true and falseval is false")
} else if(falseval == TRUE){
  print("both values are true")
} else if(trueval == FALSE){
  print("both values are false")
} else {
  print("trueval is false and falseval is true")
}
```

```{r}
stopIt <- function(){
  stop("NOT short circuited!")
}
  
if(1 == 1 || stopIt()){
  print("short circuited!")
}

if(1 == 1 | stopIt()){
  print("short circuited!")
}
```

```{r}
switchboard <- function(route){
  switch(direction,
         "northwest" = "take track 1",
         "north" = "take track 2",
         "northeast" = "take track 3",
         "this direction is not available")
}

direction <- "north"
print(switchboard(direction))
```

```{r}
direction <- "northeast"
print(switchboard(direction))
```

```{r}
direction <- "east"
print(switchboard(direction))
```

```{r}
switchnum <- function(expression)
  switch(expression,
         "option a",
         "option b",
         "option c",
         "option d")

exp <- 1

print(switchnum(exp))
```

```{r}
exp <- 5

print(switchnum(exp))
```

